### DISCUSSION TITLE
provide idempotency for occ commands

### DISCUSSION THREAD

**Discussion by tograss** [nextcloud/ansible-collection-nextcloud-admin#417] [Ideas]
Trying to keep the ticket #416 a bit clean by continuing in a discussion...

> But Nextcloud configuration is very tricky to automate and make it idempotent to say the least.
Using occ for complex configurations objets ( Im talking about php arrays, but also Delete operations of some keys ) is a pain to set through occ 

I know ! Part of why I was looking for a galaxy role was me giving up on ldap conf via occ. My idea was to have "test_command" that i would need to provide on each occ run. I attach my file occ.yml. Maybe it can provide some ideas. Sorry it's in txt format github does not like yml files...

[occ.txt](https://github.com/user-attachments/files/20911875/occ.txt)

I would install apps like this 
```yaml
- name: Enable apps
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/occ.yml"
  vars:
    test_cmd: "php{{ website.value.php.version }} --define apc.enable_cli=1 occ app:list --output=json | jq .enabled | grep -q '{{ app_enabled }}'"
    run_cmd: "app:enable {{ app_enabled }} '{{ app_enabled }}'"
  loop: "{{ nextcloud.apps.enabled }}"
  loop_control:
    loop_var: app_enabled
```

So what we could do as a first step is to allow run_occ to receive a cmd to decide if a change is needed.
When no test cmd / function is provided the behavior could stay the same.
