### ISSUE TITLE
nextcloud.admin.install_nextcloud fail if source: is not defined, but conf: is defined in nextcloud_apps

### ISSUE THREAD

**Issue by ivoruetsche** [nextcloud/ansible-collection-nextcloud-admin#335]
Hi

According to [README](https://github.com/nextcloud/ansible-collection-nextcloud-admin/tree/main/roles/install_nextcloud#applications-installation) - it should be possible to declare the conf: without the source:

```
nextcloud_apps:
  app_name_3: # Download from nextcloud official app-store
    conf:
      parameter1: ldap:\/\/ldapsrv
      parameter2: another_value
```

But, I got this error:
```
TASK [nextcloud.admin.install_nextcloud : [App] - Verify the yaml declaration for the app "xx"] *************************************************************************************************************
fatal: [198.19.220.125]: FAILED! => {
    "assertion": "(nc_app_cfg.source is defined) and (nc_app_cfg.source is string)",
    "changed": false,
    "evaluated_to": false,
    "msg": "xx is not well declared."
}
```

[This two](https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/8f5d564bcedc603205d4346db21388a390689419/roles/install_nextcloud/tasks/nc_apps.yml#L2) parts are responsible
```
- name: "[App] - Parse the item values"
  ansible.builtin.set_fact:
    nc_app_name: "{{ item.key }}"
    nc_app_source: "{{ item.value.source if item.value.source is defined else item.value }}"
    nc_app_cfg: "{{ item.value }}"

- name: "[App] - Verify the yaml declaration for the app \"{{ nc_app_name }}\""
  ansible.builtin.assert:
    that:
      - (nc_app_cfg.source is defined) and (nc_app_cfg.source is string)
    msg: "{{ nc_app_name }} is not well declared."
  when: nc_app_cfg is not string
```

Thanks a lot
Ivo
