### ISSUE TITLE
install_nextcloud: all variable names should start with `install_nextcloud_`

### ISSUE THREAD

**Issue by RussellAult** [nextcloud/ansible-collection-nextcloud-admin#365]
# Description
Currently, many of the `install_nextcloud` role's internal variables are prefixed with `nextcloud_`, but [`ansible-lint`'s `var-naming` rule](https://ansible.readthedocs.io/projects/lint/rules/var-naming/) specifies that a prefix of `role_name_` should be applied to all role-specific variables. This causes `ansible-lint` to throw errors if the role is `include`ed or `import`ed with any `vars` parameters.

# Steps to reproduce
```yaml
# roles/custom_nextcloud/tasks/main.yml

- name: Install Nextcloud
  ansible.builtin.include_role:
    name: nextcloud.admin.install_nextcloud
  vars:
    nextcloud_disable_websrv_default_site: true
```

# Expected outcome
No `ansible-lint` errors

# Actual outcome
```
$ roles/custom_nextcloud/tasks/main.yml
WARNING  Listing 1 violation(s) that are fatal
var-naming[no-role-prefix]: Variables names from within roles should use role_name_ as a prefix. (vars: nextcloud_disable_websrv_default_site)
```
